#!/usr/bin/env bash

fetch=$(dirname "$0")/fetch.sh

for arg in "${@}"; do
   if [[ "$arg" == "-h" || "$arg" == "--help" ]]; then
      echo "Resyncs test results."
      echo "    1. It cleans jsonresults directory"
      echo "    2. It calls fetch.sh with the arguments passed (bot name)"
      echo -e "    3. Accepted arguments are:\n"
      "${fetch}" "-h"
      exit $?
   fi
done

# Clean jsonresults directory.
git clean -d -f jsonresults/
git checkout -- jsonresults/

# Pull.
git checkout master
git fetch origin
git pull

# Fetch latest results from requested bots.

if [[ ${#@} -gt 0 ]]; then
   for bot in "${@}"; do
      "${fetch}" "${bot}"
   done
else
   "${fetch}"
fi
